output_root: '../'
pytorch_data_dir: '/workspace/arijit/SKJ/GraPix-master/data'
#experiment_name: "exp1_KnnPassTest1.3"
experiment_name: "exp1_GraPix"
res: 320
batch_size: 4
num_workers: 1
run_picie: False
run_crf: True
run_prediction: True
dark_mode: True
use_ddp: False
kmeans: True

model_paths:
  #- "/workspace/arijit/SKJ/GraPix-master/checkpoints/cityscapes/cityscapes_exp1_SL_KNN_CROP_NL1V2_3A_date_Mar15_11-24-17/epoch=0-step=3600.ckpt"
  - "/workspace/arijit/SKJ/GraPix-master/checkpoints/suim/directory_exp1_NONE_L3V2_date_Mar05_22-26-03/epoch=2-step=800.ckpt"

hydra:
  run:
    dir: "."
  output_subdir: ~
  #job_logging: "disabled"
  #hydra_logging: "disabled"
